import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/components/theme";
import AppProvider from "@/components/AppProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={inter.className}>
          <AppProvider>
            <Header />
            {children}
            <Footer />
          </AppProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
